#!/bin/bash
# Display access information for deployed services

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}Edge Analytics - Access Information${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""

# Check if namespace exists
if ! kubectl get namespace edge &>/dev/null; then
    echo -e "${YELLOW}Warning: 'edge' namespace not found. Have you deployed yet?${NC}"
    echo "Run: ./deploy.sh"
    exit 1
fi

echo -e "${CYAN}=== NiFi UI ===${NC}"
echo "Port Forward Command:"
echo "  kubectl port-forward -n edge svc/edge-nifi 8080:8080"
echo ""
echo "Access:"
echo "  URL: http://localhost:8080/nifi"
echo "  Username: admin"
echo "  Password: (check NiFi pod logs)"
echo ""
echo "Get Password:"
echo "  kubectl logs -n edge \$(kubectl get pods -n edge -l nifi_cr=edge-nifi -o name | head -1) | grep -i password"
echo ""

echo -e "${CYAN}=== ClickHouse ===${NC}"
echo "Port Forward Command:"
echo "  kubectl port-forward -n edge svc/clickhouse-telemetry-db 8123:8123"
echo ""
echo "Access:"
echo "  HTTP: http://localhost:8123"
echo "  Username: admin"
echo "  Password: password"
echo ""
echo "Query Example:"
echo "  curl -u admin:password 'http://localhost:8123/?query=SELECT+count(*)+FROM+telemetry.events'"
echo ""
echo "Direct Query (no port-forward):"
echo "  kubectl exec -n edge clickhouse-telemetry-db-0-0-0 -- clickhouse-client -u admin --password=password --query='SELECT count(*) FROM telemetry.events'"
echo ""

echo -e "${CYAN}=== Artemis MQTT ===${NC}"
echo "Service:"
echo "  Internal: artemis-broker.edge.svc.cluster.local:1883"
echo ""
echo "Credentials:"
echo "  Username: admin"
echo "  Password: admin"
echo ""
echo "Test MQTT (from inside cluster):"
echo "  kubectl run mqtt-test --rm -it --image=eclipse-mosquitto:latest -- \\"
echo "    mosquitto_sub -h artemis-broker.edge.svc.cluster.local -t raw-telemetry -u admin -P admin"
echo ""

echo -e "${CYAN}=== Zookeeper ===${NC}"
echo "Service:"
echo "  Internal: zookeeper-0.zookeeper.edge.svc.cluster.local:2181"
echo ""

echo -e "${CYAN}=== Redis (Dashboard Cache) ===${NC}"
echo "Port Forward Command:"
echo "  kubectl port-forward -n edge svc/edge-analytics-redis-master 6379:6379"
echo ""
echo "Access:"
echo "  Host: localhost:6379"
echo "  Password: redis-secret"
echo ""
echo "Test Redis Connection:"
echo "  redis-cli -h localhost -p 6379 -a redis-secret ping"
echo ""
echo "Check Dashboard Keys (aggregated from ClickHouse):"
echo "  redis-cli -h localhost -p 6379 -a redis-secret keys 'dashboard:*'"
echo ""
echo "Check Real-time Device Keys (from NiFi):"
echo "  redis-cli -h localhost -p 6379 -a redis-secret keys 'device:*'"
echo ""
echo "Check Real-time Stream (from NiFi):"
echo "  redis-cli -h localhost -p 6379 -a redis-secret xlen telemetry:stream"
echo ""

echo -e "${CYAN}=== Dashboard API ===${NC}"
echo "Port Forward Command:"
echo "  kubectl port-forward -n edge svc/dashboard-api 8000:8000"
echo ""
echo -e "${YELLOW}Aggregated Endpoints (from Dagster → Redis sync):${NC}"
echo "  Health:        http://localhost:8000/health"
echo "  System Health: http://localhost:8000/api/dashboard/system-health"
echo "  Device Stats:  http://localhost:8000/api/dashboard/device-stats"
echo "  Timeseries:    http://localhost:8000/api/dashboard/timeseries"
echo "  Latest Events: http://localhost:8000/api/dashboard/latest-events"
echo "  Hourly Stats:  http://localhost:8000/api/dashboard/hourly-stats"
echo "  All Data:      http://localhost:8000/api/dashboard/all"
echo ""
echo -e "${YELLOW}Real-time Endpoints (from NiFi → Redis stream):${NC}"
echo "  All Devices:   http://localhost:8000/api/realtime/devices"
echo "  Single Device: http://localhost:8000/api/realtime/device/{device_id}"
echo "  Event Stream:  http://localhost:8000/api/realtime/stream?count=100"
echo "  RT Stats:      http://localhost:8000/api/realtime/stats"
echo ""
echo "API Docs (Swagger):"
echo "  http://localhost:8000/docs"
echo ""

echo -e "${CYAN}=== Dagster (Data Orchestration) ===${NC}"
echo "Port Forward Command:"
echo "  kubectl port-forward -n edge svc/edge-analytics-dagster-webserver 3001:80"
echo ""
echo "Access:"
echo "  UI: http://localhost:3001"
echo ""
echo "Features:"
echo "  - View all scheduled jobs and their status"
echo "  - Monitor asset lineage and data quality"
echo "  - Trigger manual runs and backfills"
echo "  - View logs and execution history"
echo ""
echo "Jobs:"
echo "  - redis_sync_job (every minute)"
echo "  - hourly_aggregation_job (hourly)"
echo "  - daily_aggregation_job (daily 1 AM)"
echo "  - clickhouse_maintenance_job (daily 3 AM)"
echo "  - data_quality_job (hourly)"
echo ""

echo -e "${CYAN}=== Grafana (Monitoring) ===${NC}"
echo "Port Forward Command:"
echo "  kubectl port-forward -n edge svc/edge-analytics-grafana 3000:80"
echo ""
echo "Access:"
echo "  UI: http://localhost:3000"
echo "  Username: admin"
echo "  Password: admin-secret"
echo ""
echo "Pre-configured Dashboards:"
echo "  - Edge Analytics Overview (telemetry metrics)"
echo "  - ClickHouse Metrics (database performance)"
echo "  - Pipeline Health (NiFi, Redis, Dagster)"
echo ""
echo "Data Sources:"
echo "  - Prometheus (metrics)"
echo "  - ClickHouse (telemetry data)"
echo "  - Redis (cache data)"
echo ""

echo -e "${CYAN}=== Prometheus (Metrics) ===${NC}"
echo "Port Forward Command:"
echo "  kubectl port-forward -n edge svc/edge-analytics-prometheus-server 9090:80"
echo ""
echo "Access:"
echo "  UI: http://localhost:9090"
echo ""
echo "Scraped Targets:"
echo "  - ClickHouse (:9363)"
echo "  - NiFi (:9092)"
echo "  - Redis (:9121)"
echo "  - Node Exporter"
echo ""

echo -e "${CYAN}=== Quick Commands ===${NC}"
echo "Check all pods:"
echo "  kubectl get pods -n edge"
echo ""
echo "Check custom resources:"
echo "  kubectl get nificlusters,clickhouseinstallations -n edge"
echo ""
echo "Deploy test producer:"
echo "  helm install producer charts/producer/ -n edge"
echo ""
echo "Open all UIs (run in separate terminals):"
echo "  kubectl port-forward -n edge svc/edge-nifi 8080:8080                    # NiFi"
echo "  kubectl port-forward -n edge svc/edge-analytics-grafana 3000:80         # Grafana"
echo "  kubectl port-forward -n edge svc/edge-analytics-dagster-webserver 3001:80  # Dagster"
echo "  kubectl port-forward -n edge svc/dashboard-api 8000:8000                # API"
echo ""

echo -e "${GREEN}=========================================${NC}"
echo ""